### PR TITLE
Fix bug with Option and Result impls

### PR DESCRIPTION
**Pull request by nico-abram**

### CODE REVIEW

**Comment by nico-abram** [comment]
I just realized the same thing can be done for the Result impl if you think this is worth merging

**Comment by nico-abram** [comment]
I just realized this probably breaks things since some copy() impls modify the input and you probably intentionally used a local stack copy. Apologies

(I just checked that the tests worked)

**Comment by nico-abram** [comment]
I'm actually a bit confused now, because the tuple impl does not seem to pass a copy down the stack (And instead uses the parameter that comes in) https://github.com/frankmcsherry/columnation/blob/master/src/lib.rs#L340-L343

**Comment by nico-abram** [comment]
After thinking about this some more, is passing a copy in Option/Result not a bug?

Take this example:

```rs
fn test() {
    let record = Some(format!("grawwwwrr!"));
    // prepare encoded data for bencher.bytes
    let mut arena = ColumnStack::default();
    for _ in 0..100 {
        arena.copy(&record);
    }
    for element in arena.iter() {
        dbg!(element as *const _ as usize);
        dbg!(element.as_ref().unwrap().as_ptr() as usize);
        assert!(element == &record);
    }
        dbg!(arena.iter().next().unwrap().as_ref().unwrap().as_ptr() as usize);
        dbg!(record.as_ref().unwrap().as_ptr() as usize);
}
```

On my machine, this gives the same address for all the string contents:
```
[tests\tests.rs:12] element as *const _ as usize = 2287633394200
[tests\tests.rs:13] element.as_ref().unwrap().as_bytes().as_ptr() as usize = 2287633374112
[tests\tests.rs:12] element as *const _ as usize = 2287633394224
[tests\tests.rs:13] element.as_ref().unwrap().as_bytes().as_ptr() as usize = 2287633374112
[tests\tests.rs:12] element as *const _ as usize = 2287633394248
[tests\tests.rs:13] element.as_ref().unwrap().as_bytes().as_ptr() as usize = 2287633374112
[tests\tests.rs:16] arena.iter().next().unwrap().as_ref().unwrap().as_bytes().as_ptr() as usize = 2287633374112
[tests\tests.rs:17] record.as_ref().unwrap().as_bytes().as_ptr() as usize = 2287633374112
```

With the change in this PR I get this:
```
[tests\tests.rs:12] element as *const _ as usize = 2575442470152
[tests\tests.rs:13] element.as_ref().unwrap().as_bytes().as_ptr() as usize = 2575442476950
[tests\tests.rs:12] element as *const _ as usize = 2575442470176
[tests\tests.rs:13] element.as_ref().unwrap().as_bytes().as_ptr() as usize = 2575442476960
[tests\tests.rs:12] element as *const _ as usize = 2575442470200
[tests\tests.rs:13] element.as_ref().unwrap().as_bytes().as_ptr() as usize = 2575442476970
[tests\tests.rs:16] arena.iter().next().unwrap().as_ref().unwrap().as_bytes().as_ptr() as usize = 2575442451744
[tests\tests.rs:17] record.as_ref().unwrap().as_bytes().as_ptr() as usize = 2575442451584
```

And I think the problem is the write to the out-param in the String impl (https://github.com/frankmcsherry/columnation/blob/master/src/lib.rs#L319) writes to the stack copy (https://github.com/frankmcsherry/columnation/blob/master/src/lib.rs#L136) which is not used for anything else, and then what actually gets pushed to the `local` vec in the ColumnStack by copy() is the same bits that were passed into it (Which has a pointer somewhere else, to memory owned by the String being copied)

Here's an example showing that:

```rs
fn test2() {
    let mut record = Some(format!("grawwwwrr!"));
    // prepare encoded data for bencher.bytes
    let mut arena = ColumnStack::default();
    arena.copy(&record);

    println!("{:?}", &arena.iter().next());
    record.as_mut().unwrap().pop();
    record.as_mut().unwrap().push('a');
    println!("{:?}", &record);
    println!("{:?}", &arena.iter().next());
}
```

Output:
```
Some(Some("grawwwwrr!"))
Some("grawwwwrra")
Some(Some("grawwwwrra"))
```

With this change:
```
Some(Some("grawwwwrr!"))
Some("grawwwwrra")
Some(Some("grawwwwrr!"))
```

**Comment by frankmcsherry** [comment]
Ah, these look like bugs for sure. At the same time, the reason I didn't use the more natural version is that it forms a `&mut` reference that I don't know has the guarantees that Rust wants for UB-free code (in particular, it references something that is also referenced by a `&` pointer). My hunch/hope was that by staying with raw pointers, the code would be less likely to fall afoul of aliasing UB.

The previous version of the code had a signature that looked like
```rust
/// # Safety 
///
/// Return value must not be dropped.
/// (ed: `ManuallyDrop` seems great here).
fn unsafe copy(&mut self, item: &T) -> T {
    // read `item`, create a new proxy value copying it
}
```
where `item` would be traversed without potential pointer aliasing, and the unsafety was restricted (I think) to `Vec::from_raw_parts`, roughly.

I think in this case (for `Option` and `Result`) that would be more clear. Should I try out that code in a branch to show you what it looks like?

**Comment by nico-abram** [comment]
That makes a lot of sense. I wonder if &raw mut would help there

**Comment by frankmcsherry** [comment]
I think the bug has been fixed with the new `fn copy` signature, in #5. Closing, though I appreciating you flagging the bug!

**Pull request closed without merging**
